"""empty message

Revision ID: 37ea1bf7be3e
Revises: cfef3ff15651
Create Date: 2025-01-28 23:04:36.471341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '37ea1bf7be3e'
down_revision: Union[str, None] = 'cfef3ff15651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersetting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setting', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersetting', schema=None) as batch_op:
        batch_op.drop_column('setting')

    # ### end Alembic commands ###
