"""empty message

Revision ID: 55669a3483ff
Revises: 37ea1bf7be3e
Create Date: 2025-01-29 23:10:28.675800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '55669a3483ff'
down_revision: Union[str, None] = '37ea1bf7be3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersetting', schema=None) as batch_op:
        batch_op.drop_column('emotion_colors')
        batch_op.drop_column('use_openai_chatting')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersetting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_openai_chatting', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('emotion_colors', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
