"""empty message

Revision ID: b3c9d4a826f4
Revises: 9195c0e47694
Create Date: 2025-01-23 23:15:18.031557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b3c9d4a826f4'
down_revision: Union[str, None] = '9195c0e47694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('greeting')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('greeting',
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###
