"""empty message

Revision ID: cfef3ff15651
Revises: e9ee3a5fa137
Create Date: 2025-01-27 22:22:50.998866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cfef3ff15651'
down_revision: Union[str, None] = 'e9ee3a5fa137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersetting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_openai_chatting', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usersetting', schema=None) as batch_op:
        batch_op.drop_column('use_openai_chatting')

    # ### end Alembic commands ###
