"""empty message

Revision ID: e9ee3a5fa137
Revises: b3c9d4a826f4
Create Date: 2025-01-27 14:42:08.635615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e9ee3a5fa137'
down_revision: Union[str, None] = 'b3c9d4a826f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersetting',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emotion_colors', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('color')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('emotion_colors', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('usersetting')
    # ### end Alembic commands ###
